/* eslint-disable @next/next/no-sync-scripts */
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "تیام",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          http-equiv="Permissions-Policy"
          content="interest-cohort=(), user-id=()"
        />
      </Head>
      {/* <Script type="text/javascript" src="otp.js" /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
